### ISSUE TITLE
Issue with singleton implementation in chapter 2

### ISSUE THREAD

**Issue by RKWesdijk** [PacktPublishing/Hands-On-Enterprise-Application-Development-with-Python#2]
With chapter 2 Singleton with python 3.8.2 I get the following error:

```
>>> dbobj1 = Database("example.com",5432,"joe","changeme","testdb")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/Development/bugzot/meta/Singleton.py", line 7, in __call__
    cls._instance_registry[cls] = super().__init__(*args, **kwargs)
TypeError: type.__init__() takes 1 or 3 arguments
```

Also tried the single file version on this repository but same thing happens.

It seems to work when I change the `super().__init__(*args,**kwargs)` to `super().__call__(*args,**kwargs)` as per https://www.python-course.eu/python3_metaclasses.php

Have not tested it in other python versions.

//obviously there are double _ surrounding the init and the call but they seem to get lost in markup.

**Comment by h4xr** [comment]
@RKWesdijk thanks a lot for pointing this out. Your finding is correct about the issue.
It should be `super().__call__(*args, **kwargs)`

I will update the code to reflect the same

**Comment by h4xr** [comment]
I have pushed a commit correcting the issue in the singleton code, which should run in an expected manner now :)
Thanks a lot again for pointing out
